env:
  global:
    - CC_TEST_REPORTER_ID=4e4deba4c64a86f11156bf8b1b7f4960afacf264798b29c30c1a3aee098c77c2
language: go
go:
  - tip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  # Test
  - go test ./... -coverprofile=c.out -covermode=atomic
  # Ensure examples build
  - for app in $(ls examples/ -F | grep /); do go build "github.com/efritz/scarf/examples/$app"; done
after_script:
  - ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
